---

- name: reload webserver
  become: yes
  service: name=nginx state=reloaded

- name: restart webserver
  become: yes
  service: name=nginx state=restarted

- name: reload php
  become: yes
  service: name='php{{ php_version }}-fpm' state=reloaded

- name: restart php
  become: yes
  service: name='php{{ php_version }}-fpm' state=restarted
