---

- name: Setting up base system
  hosts: [all]
  roles:
    - common/apt
    - common/ssh
    - common/locales
    - common/tools
  tags: system

- name: Setting up lairdubois requirements
  hosts: [all]
  roles:
    - database
    - php
    - nodejs
    - search
    - webserver
    - certs
  tags: config

- name: Setting up lairdubois application
  hosts: [all]
  roles:
    - lairdubois
  tags: app
