---

- name: Setting up base system
  hosts: [all]
  remote_user: debian
  roles:
    - common/apt
    - common/ssh
    - common/tools
  tags: system

- name: Setting up lairdubois requirements
  hosts: [all]
  remote_user: debian
  roles:
    - database
    - php
    - nodejs
    - search
    - webserver
  tags: config

- name: Setting up lairdubois application
  hosts: [all]
  remote_user: debian
  roles:
    - app/lairdubois
  tags: app
