---

- name: Setting up base system
  hosts: [all]
  remote_user: debian
  roles:
    - common/apt
    - common/ssh
    - common/tools

- name: Setting up lairdubois
  hosts: [all]
  remote_user: debian
  roles:
    - database
    - php
    - webserver
