---

- name: create web directory {{ app_dir }}
  become: yes
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: clone lairdubois application
  git:
    repo: https://github.com/lairdubois/lairdubois.git
    dest: "{{ app_dir }}"

- import_tasks: app.yml
- import_tasks: database.yml
- import_tasks: webserver.yml
