---

- name: create technical group
  become: yes
  group:
    name: ladb

- name: create technical user
  become: yes
  user:
    name: ladb
    group: ladb

- name: create web directory /var/www/{{ main_host }}
  become: true
  file:
    path: /var/www/{{ main_host }}
    state: directory
    owner: ladb
    group: ladb
