---

- name: create ladb app group '{{ ladb_app_group }}'
  become: yes
  group:
    name: "{{ ladb_app_group }}"
    state: present

- name: add users to new ladp app group
  become: yes
  user:
    append: yes
    groups: "{{ ladb_app_group }}"
    name: "{{ item }}"
  with_items:
    - www-data
    - "{{ ansible_user }}"

- name: create web directory {{ app_dir }}
  become: yes
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: clone lairdubois application
  git:
    repo: https://github.com/marcaurele/lairdubois.git
    dest: "{{ app_dir }}"
    version: fix-jquery-ui

- name: modify app directory rights
  become: yes
  file:
    path: '{{ item }}'
    state: directory
    group: "{{ ladb_app_group }}"
    mode: 02775
  loop:
    - '{{ app_dir }}/var'
    - '{{ app_dir }}/var/cache'
    - '{{ app_dir }}/var/logs'
  notify:
    - reload php
    - reload nginx

- import_tasks: app.yml
- import_tasks: webserver.yml
