---

- name: create web directory /var/www/{{ main_host }}
  become: yes
  file:
    path: /var/www/{{ main_host }}
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: clone lairdubois application
  git:
    repo: https://github.com/lairdubois/lairdubois.git
    dest: /var/www/{{ main_host }}/
