---
# Customized variables by environment
env: qa

elasticsearch_memory: 1g
acme_email_notice: "{{ vault_acme_email_notice }}"
domains:
  - "{{ vault_main_domain }}"
host_aliases:
  - "{{ vault_main_host }}"

app_index: app_beta.php
