---

- name: deploy lairdubois configuration
  template:
    dest: "{{ app_dir }}/app/config/parameters.yml"
    src: parameters.yml.j2

- name: perform composer install
  command: composer --no-interaction install
  args:
    chdir: "{{ app_dir }}"

- name: compile and minimize CSS and JS
  command: bin/console --no-interaction --env={{ symfony_env }} assetic:dump
  args:
    chdir: "{{ app_dir }}"

- name: install bundle's assets
  command: bin/console --no-interaction --env={{ symfony_env }} assets:install
  args:
    chdir: "{{ app_dir }}"

- import_tasks: database.yml

- name: initialize ehcache index
  command: bin/console --no-interaction --env={{ symfony_env }} fos:elastica:populate
  args:
    chdir: "{{ app_dir }}"

# - name: create initial user
#   command: bin/console fos:user:create
#   args:
#     chdir: "{{ app_dir }}"
