---

- name: copy db backup
  copy:
    src: "{{ import_db_file }}"
    dest: /tmp/db_data.sql.gz
  when: import_db_file is defined

- name: import db backup
  become: yes
  shell: zcat /tmp/db_data.sql.gz | mysql {{ ladb_database_name }}
  when: import_db_file is defined

- name: inject database schema
  command: bin/console --no-interaction --env={{ symfony_env }} doctrine:schema:update --force
  args:
    chdir: '{{ app_dir }}'
  register: db_schema_action
  changed_when: '"Database schema updated successfully" in db_schema_action.stdout'

- name: inject extra sessions schema
  become: yes
  shell: mysql {{ ladb_database_name }} < {{ app_dir }}/docs/database/schema-sessions.sql
  when: db_schema_action.changed
