---

- name: set fact for symfony env
  set_fact:
    symfony_env: "{% if debug %}dev{% else %}prod{% endif %}"

- name: create ladb application group '{{ ladb_app_group }}'
  become: yes
  group:
    name: "{{ ladb_app_group }}"
    state: present

- name: add users to new ladp application group
  become: yes
  user:
    append: yes
    groups: "{{ ladb_app_group }}"
    name: "{{ item }}"
  with_items:
    - www-data
    - "{{ ansible_user }}"

- name: create web directory {{ app_dir }}
  become: yes
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: clone lairdubois application
  git:
    repo: https://github.com/lairdubois/lairdubois.git
    dest: '{{ app_dir }}'
    force: yes
  when: vagrant is not defined or not vagrant

- name: create and modify extra directories for ladb
  become: yes
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ladb_app_group }}'
    mode: 02775
    recurse: yes
  loop:
    - '{{ app_dir }}/var'
    - '{{ app_dir }}/uploads'
    - '{{ app_dir }}/web/media'
  notify:
    - restart php
    - restart webserver
  when: vagrant is not defined or not vagrant

- import_tasks: app.yml
- import_tasks: webserver.yml

- name: modify application directory rights for var once again
  become: yes
  file:
    path: '{{ item }}'
    state: directory
    group: '{{ ladb_app_group }}'
    mode: 02775
    recurse: yes
  loop:
    - '{{ app_dir }}/var'
  notify:
    - restart php
    - restart webserver
  when: vagrant is not defined or not vagrant

- name: crontab for ladb application
  become: yes
  cron:
    name: '{{ item.name }}'
    job: '{{ item.job }}'
    minute: '{{ item.minute | default("*") }}'
    hour: '{{ item.hour | default("*") }}'
    day: '{{ item.day | default("*") }}'
    month: '{{ item.month | default("*") }}'
    weekday: '{{ item.weekday | default("*") }}'
  loop: '{{ ladb_crontab_list }}'
  when: ladb_crontab_install

- import_tasks: services.yml
