---

- name: create configuration directory for certificates
  become: yes
  file:
    path: /etc/certs
    state: directory
    owner: root
    group: root
    mode: 0711

- import_tasks: acme.yml
  when: acme_certificate

- import_tasks: selfsigned.yml
  when: not acme_certificate
