---

- name: install tools packages
  become: yes
  apt:
    pkg: "{{ item }}"
    state: latest
  with_together:
    - apt-transport-https
    - apt-utils
    - bash
    - bash-completion
    - ca-certificates
    - curl
    - default-jre
    - ghostscript
    - git
    - htop
    - imagemagick
    - jpegoptim
    - librsvg2-bin
    - lsb-release
    - optipng
    - pngquant
    - rabbitmq-server
    - tzdata
    - unzip
    - util-linux
    - zip
