---

- name: configure sshd
  become: yes
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart ssh

- name: setup global known_hosts
  become: yes
  known_hosts:
    path: /etc/ssh/known_hosts
    name: "{{ item }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -T 10 -H -t rsa ' + item) }}"
    state: present
  loop:
    - github.com

- name: add authorized ssh keys from {{ github_keys }}
  authorized_key:
    key: "{{ item.key }}"
    comment: "{{ item.name }}"
    state: present
    user: "{{ ansible_user_id }}"
  loop: "{{ ssh_keys }}"
