---

# Unsure about PHP, shall we use Debian-testing which has PHP 7.2?
- name: add repository GPG key for PHP7.1
  become: yes
  apt_key:
    url: https://packages.sury.org/php/apt.gpg

- name: add repository for PHP7.1
  become: yes
  apt_repository:
    repo: deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main
  register: php_repo

- name: update apt cache
  become: yes
  apt:
    update_cache: yes
  when: php_repo.changed

- name: install PHP7.1
  become: yes
  apt:
    pkg: "{{ item }}"
  with_together:
    - php7.1
    - php7.1-cli
    - php7.1-curl
    - php7.1-intl
    - php7.1-gd
    - php7.1-imagick
    - php7.1-mysql
    - php7.1-fpm
    - php7.1-mbstring
    - php7.1-xml
    - php7.1-zip
    - php7.1-bz2
    - php7.1-gmp
    - php7.1-bcmath

- name: configure FPM
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: fpm-php.ini.j2
      dest: /etc/php/7.1/fpm/php.ini
    - src: fpm-www.conf.j2
      dest: /etc/php/7.1/fpm/pool.d/www.conf
  notify: restart php

# Unsure about composer, shall we used Debian-testing which includes a more up-to-date version?
- name: fetch composer install script
  become: yes
  get_url:
    force: yes
    dest: ~/composer-installer.php
    url: https://getcomposer.org/installer

- name: install composer
  become: yes
  command: php ~/composer-installer.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
