---

# Unsure about PHP, shall we use Debian-testing which has PHP 7.2?
- name: add repository GPG key for PHP
  become: yes
  apt_key:
    url: https://packages.sury.org/php/apt.gpg

- name: add repository for PHP
  become: yes
  apt_repository:
    repo: deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main

- name: install PHP {{ php_version }}
  become: yes
  apt:
    pkg: "{{ item }}"
  with_together:
    - "php{{ php_version }}"
    - "php{{ php_version }}-cli"
    - "php{{ php_version }}-curl"
    - "php{{ php_version }}-intl"
    - "php{{ php_version }}-gd"
    - "php{{ php_version }}-imagick"
    - "php{{ php_version }}-mysql"
    - "php{{ php_version }}-fpm"
    - "php{{ php_version }}-mbstring"
    - "php{{ php_version }}-xml"
    - "php{{ php_version }}-zip"
    - "php{{ php_version }}-bz2"
    - "php{{ php_version }}-gmp"
    - "php{{ php_version }}-bcmath"

- name: configure FPM
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: fpm-php.ini.j2
      dest: "/etc/php/{{ php_version }}/fpm/php.ini"
    - src: fpm-www.conf.j2
      dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
  notify: restart php

# Unsure about composer, shall we used Debian-testing which includes a more up-to-date version?
- name: fetch composer install script
  become: yes
  get_url:
    force: yes
    dest: ~/composer-installer.php
    url: https://getcomposer.org/installer

- name: install composer
  become: yes
  command: php ~/composer-installer.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
