---

- name: install nginx packages
  become: yes
  apt:
    pkg: "nginx"

- name: change nginx default configuration
  become: yes
  template:
    dest: /etc/nginx/nginx.conf
    src: nginx.conf.j2
    validate: nginx -t -c %s
  notify: reload nginx
